# Generated by Django 5.0.6 on 2024-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อ")),
                (
                    "student_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
                ("major", models.CharField(max_length=255, verbose_name="สาขา")),
                ("faculty", models.CharField(max_length=255, verbose_name="คณะ")),
            ],
        ),
    ]
