# Generated by Django 5.0.6 on 2024-05-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythesis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="ชื่อเรื่องวิทยานิพนธ์"
                    ),
                ),
                (
                    "advisor",
                    models.CharField(max_length=255, verbose_name="อาจารย์ที่ปรึกษา"),
                ),
                ("abstract", models.TextField(verbose_name="บทคัดย่อ")),
                ("keywords", models.CharField(max_length=255, verbose_name="คำสำคัญ")),
                (
                    "document",
                    models.FileField(upload_to="thesis/", verbose_name="ไฟล์เอกสาร"),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่อัปโหลด"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้เขียน",
                    ),
                ),
            ],
        ),
    ]
