# Generated by Django 5.0.6 on 2024-05-09 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythesis", "0002_thesis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="student_id",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="รหัสนักศึกษา"
            ),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
