# Generated by Django 5.0.6 on 2024-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythesis", "0003_alter_students_student_id_alter_thesis_upload_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อ")),
                (
                    "student_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="รหัสนักศึกษา"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="อีเมล"
                    ),
                ),
                ("major", models.CharField(max_length=255, verbose_name="สาขา")),
                ("faculty", models.CharField(max_length=255, verbose_name="คณะ")),
            ],
        ),
        migrations.DeleteModel(
            name="Students",
        ),
        migrations.AlterField(
            model_name="thesis",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, default=1, verbose_name="วันที่อัปโหลด"
            ),
            preserve_default=False,
        ),
    ]
